"""update user

Revision ID: 0de0e31fffb3
Revises: 140674aea259
Create Date: 2024-06-07 12:08:33.829211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0de0e31fffb3'
down_revision = '140674aea259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.Text(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
